### ISSUE TITLE
Git URL sources need more sanity checking

### ISSUE THREAD

**Issue by takikawa** [racket/pkg-index#4]
Using a git URL like `"git://github.com/b>"` results in an error when using the package site.

One that looks like:

````
cadr: contract violation
  expected: (cons/c any/c pair?)
  given: '("b>")
  context...:
````

This is due to using `package-url->checksum` directly. It looks like `raco pkg install` protects against this by sanity checking the URL, so the package index should probably do that too before handing it off.
